# Generated by Django 3.2.25 on 2025-02-16 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_user_profiles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_profiles',
            new_name='user_profile',
        ),
    ]
